runtime: python37

instance_class: F2

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

#runtime: python27
#api_version: 1
#threadsafe: True

#handlers:
#- url: /.*
#  script: main.app


